"""cria conversas e mensagens

Revision ID: 37a1c9add2cd
Revises:
Create Date: 2026-07-10 09:27:55.769820

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37a1c9add2cd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criada_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("tokens_entrada", sa.Integer(), nullable=False),
        sa.Column("tokens_saida", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mensagens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversa_id", sa.Uuid(), nullable=False),
        sa.Column("ordem", sa.Integer(), nullable=False),
        sa.Column(
            "papel", sa.Enum("USUARIO", "ASSISTENTE", name="papeldamensagem"), nullable=False
        ),
        sa.Column("conteudo", sa.Text(), nullable=False),
        sa.Column(
            "criada_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["conversa_id"], ["conversas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversa_id", "ordem", name="mensagem_unica_por_ordem"),
    )
    op.create_index(op.f("ix_mensagens_conversa_id"), "mensagens", ["conversa_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mensagens_conversa_id"), table_name="mensagens")
    op.drop_table("mensagens")
    op.drop_table("conversas")
    # ### end Alembic commands ###
